
#mongoDB
spring:
 data:
  mongodb:
   # host: localhost
    #port: 27017
    database: passwordmanager
    
spring.data.mongodb.uri: mongodb+srv://password_manager:GiH43OTCDYOP7igx@noahcluster-uqr8c.azure.mongodb.net/test?retryWrites=true&w=majority

#Spring Boot Security
spring.security.user.name: Test
spring.security.user.password: 4321
